#!/usr/bin/env python3
"""
generate_mpl_theme.py
Generates matplotlib .mplstyle theme file for Context A (AI OS System).
Reads extracted tokens from specs/SPEC_CONTEXT_A.md or context_a_extracted.json.

Usage:
  python3 generate_mpl_theme.py \
    --spec ../specs/SPEC_CONTEXT_A.md \
    --output ../skills/infographic/assets/mpl-themes/ai_os_system.mplstyle
"""

import argparse
import json
import os
import re
import sys

# ──────────────────────────────────────────────
# DEFAULT TOKENS (fallback if extraction failed)
# These should be updated once Wibify extraction completes
# ──────────────────────────────────────────────
DEFAULTS = {
    'bg_void':       '#080810',
    'bg_base':       '#0d0d14',
    'bg_surface':    '#12121e',
    'bg_elevated':   '#1a1a2e',
    'border':        '#1f1f35',
    'accent_primary': '#00E5CC',   # ← Update from Wibify extraction
    'accent_warning': '#E8B931',
    'accent_danger':  '#FF6B6B',
    'accent_sys':     '#7B68EE',
    'text_primary':  '#EEEAE4',
    'text_secondary':'#A09D95',
    'text_muted':    '#606060',
}

# Color cycle for multi-series charts (accent first, then supporting)
COLOR_CYCLE = [
    '{accent_primary}',
    '{accent_warning}',
    '{accent_sys}',
    '{accent_danger}',
    '#A09D95',  # neutral last
]


def load_tokens_from_spec(spec_path):
    """Try to extract hex values from the SPEC_CONTEXT_A.md file."""
    tokens = DEFAULTS.copy()
    
    if not os.path.exists(spec_path):
        print(f"Warning: spec file not found at {spec_path}, using defaults")
        return tokens
    
    with open(spec_path, 'r') as f:
        content = f.read()
    
    # Look for [EXTRACTED] placeholders — if they're filled, use them
    # Pattern: | `--a-accent-primary` | `#HEXVALUE` |
    token_pattern = re.compile(r'`--a-([a-z-]+)`\s*\|\s*`(#[0-9a-fA-F]{6})`')
    
    for match in token_pattern.finditer(content):
        raw_key = match.group(1)
        hex_val = match.group(2)
        
        # Map CSS token names to Python dict keys
        key_map = {
            'bg-void': 'bg_void',
            'bg-base': 'bg_base',
            'bg-surface': 'bg_surface',
            'bg-elevated': 'bg_elevated',
            'border': 'border',
            'accent-primary': 'accent_primary',
            'accent-warning': 'accent_warning',
            'accent-danger': 'accent_danger',
            'accent-sys': 'accent_sys',
            'text-primary': 'text_primary',
            'text-secondary': 'text_secondary',
            'text-muted': 'text_muted',
        }
        
        if raw_key in key_map and hex_val != '#???':
            tokens[key_map[raw_key]] = hex_val
            print(f"  Loaded from spec: {raw_key} = {hex_val}")
    
    # Also try loading from extracted JSON
    json_path = os.path.join(os.path.dirname(spec_path), 'context_a_extracted.json')
    if os.path.exists(json_path):
        with open(json_path, 'r') as f:
            extracted = json.load(f)
        
        mapping = extracted.get('semantic_mapping', {})
        json_key_map = {
            'bg-void': 'bg_void',
            'bg-base': 'bg_base',
            'bg-surface': 'bg_surface',
            'bg-elevated': 'bg_elevated',
            'border': 'border',
            'accent-primary': 'accent_primary',
            'text-primary': 'text_primary',
            'text-secondary': 'text_secondary',
        }
        for k, v in mapping.items():
            if k in json_key_map and v and v.startswith('#') and 'PLACEHOLDER' not in v:
                tokens[json_key_map[k]] = v
                print(f"  Loaded from JSON: {k} = {v}")
    
    return tokens


def build_color_cycle(tokens):
    """Build the color cycle string for matplotlib."""
    colors = []
    for c in COLOR_CYCLE:
        resolved = c.format(**tokens)
        colors.append(resolved)
    return ', '.join(colors)


def generate_mplstyle(tokens):
    """Generate the .mplstyle file content."""
    cycle = build_color_cycle(tokens)
    
    style = f"""# AI OS System — Matplotlib Brand Theme
# Context A: Wibify-inspired / Obsidian Aurora
# Generated by generate_mpl_theme.py
# Update accent_primary if Wibify extraction was incomplete

# ── Figure ────────────────────────────────────────────
figure.facecolor:          {tokens['bg_base']}
figure.edgecolor:          {tokens['border']}
figure.figsize:            12, 7
figure.dpi:                100
figure.titlesize:          14
figure.titleweight:        bold
figure.titlecolor:         {tokens['text_primary']}

# ── Axes ──────────────────────────────────────────────
axes.facecolor:            {tokens['bg_surface']}
axes.edgecolor:            {tokens['border']}
axes.linewidth:            0.8
axes.labelcolor:           {tokens['text_secondary']}
axes.labelsize:            11
axes.labelpad:             8
axes.titlesize:            13
axes.titleweight:          bold
axes.titlecolor:           {tokens['text_primary']}
axes.titlepad:             14
axes.spines.top:           False
axes.spines.right:         False
axes.spines.left:          True
axes.spines.bottom:        True
axes.grid:                 True
axes.axisbelow:            True

# Color cycle — accent first
axes.prop_cycle:           cycler('color', [{cycle}])

# ── Grid ──────────────────────────────────────────────
grid.color:                {tokens['bg_elevated']}
grid.linewidth:            0.6
grid.alpha:                0.8
grid.linestyle:            --

# ── Tick marks ────────────────────────────────────────
xtick.color:               {tokens['text_secondary']}
xtick.labelsize:           10
xtick.labelcolor:          {tokens['text_secondary']}
xtick.direction:           out
xtick.major.size:          4
xtick.minor.visible:       False

ytick.color:               {tokens['text_secondary']}
ytick.labelsize:           10
ytick.labelcolor:          {tokens['text_secondary']}
ytick.direction:           out
ytick.major.size:          4
ytick.minor.visible:       False

# ── Legend ────────────────────────────────────────────
legend.facecolor:          {tokens['bg_elevated']}
legend.edgecolor:          {tokens['border']}
legend.fontsize:           10
legend.labelcolor:         {tokens['text_primary']}
legend.framealpha:         1.0
legend.borderpad:          0.6
legend.labelspacing:       0.4

# ── Lines ─────────────────────────────────────────────
lines.linewidth:           2.0
lines.markersize:          6

# ── Bars ──────────────────────────────────────────────
patch.linewidth:           0
patch.edgecolor:           none

# ── Text ──────────────────────────────────────────────
text.color:                {tokens['text_primary']}
font.family:               sans-serif
font.sans-serif:           DM Sans, Inter, Helvetica Neue, Arial, sans-serif
font.size:                 11

# ── Savefig ───────────────────────────────────────────
savefig.facecolor:         {tokens['bg_base']}
savefig.edgecolor:         none
savefig.dpi:               150
savefig.bbox:              tight
savefig.pad_inches:        0.15
"""
    return style


def validate_style(output_path):
    """Validate the generated style file by loading it."""
    try:
        import matplotlib
        matplotlib.style.use(output_path)
        print("  ✅ Theme validation passed")
        return True
    except Exception as e:
        print(f"  ⚠️  Theme validation warning: {e}")
        print("     File may still work — matplotlib version differences.")
        return False


def main():
    parser = argparse.ArgumentParser(description='Generate matplotlib brand theme')
    parser.add_argument('--spec', default='../specs/SPEC_CONTEXT_A.md',
                        help='Path to SPEC_CONTEXT_A.md')
    parser.add_argument('--output', default='../skills/infographic/assets/mpl-themes/ai_os_system.mplstyle',
                        help='Output path for .mplstyle file')
    args = parser.parse_args()

    print("Generating AI OS System matplotlib theme...")
    
    # Load tokens
    print(f"\nLoading tokens from: {args.spec}")
    tokens = load_tokens_from_spec(args.spec)
    
    # Check if accent-primary is still a placeholder
    if tokens['accent_primary'] in ('#PLACEHOLDER', '#???', ''):
        print("\n⚠️  WARNING: accent_primary is a placeholder.")
        print("   The theme will use #00E5CC as fallback.")
        print("   Update after Wibify extraction completes.")
        tokens['accent_primary'] = '#00E5CC'
    
    print(f"\nKey tokens being used:")
    print(f"  bg_base:        {tokens['bg_base']}")
    print(f"  bg_surface:     {tokens['bg_surface']}")
    print(f"  accent_primary: {tokens['accent_primary']} ← SIGNATURE COLOR")
    print(f"  text_primary:   {tokens['text_primary']}")
    
    # Generate style content
    style_content = generate_mplstyle(tokens)
    
    # Write output
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, 'w') as f:
        f.write(style_content)
    
    print(f"\n✅ Theme written to: {args.output}")
    
    # Validate
    print("\nValidating theme...")
    validate_style(args.output)
    
    print(f"\nUsage in Python:")
    print(f"  import matplotlib")
    print(f"  matplotlib.style.use('{args.output}')")
    print(f"  import matplotlib.pyplot as plt")
    print(f"  # Your plotting code here")


if __name__ == '__main__':
    main()
