import { NextResponse } from 'next/server';
import { queryOne } from '@/lib/db';
import type { ContentPost } from '@/lib/types';
import { readFile, readdir } from 'fs/promises';
import path from 'path';
import archiver from 'archiver';
import { PassThrough } from 'stream';
import { getContentPipelineRoot } from '@/lib/pipeline-paths';

export const dynamic = 'force-dynamic';

const CHANNEL_META: Record<string, { label: string; dimensions: string; charLimit?: number }> = {
  instagram: { label: 'Instagram', dimensions: '1080×1080' },
  twitter: { label: 'X / Twitter', dimensions: '1200×675', charLimit: 280 },
  facebook: { label: 'Facebook', dimensions: '1200×630' },
  linkedin: { label: 'LinkedIn', dimensions: '1200×630' },
};

function formatDate(d: string | null): string {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
}

function buildPostCopyText(post: ContentPost): string {
  const lines: string[] = [];
  const divider = '═'.repeat(56);
  const sectionDiv = '─'.repeat(56);

  lines.push(divider);
  lines.push('  BHARATVARSH CONTENT PIPELINE — POST PACK');
  lines.push(divider);
  lines.push('');
  lines.push(`Post ID:     ${post.post_id}`);
  lines.push(`Topic:       ${post.topic}`);
  lines.push(`Campaign:    ${post.campaign}`);
  if (post.scheduled_date) {
    lines.push(`Scheduled:   ${formatDate(post.scheduled_date)}${post.scheduled_time ? ' ' + post.scheduled_time : ''}`);
  }
  if (post.story_angle) lines.push(`Story Angle: ${post.story_angle}`);
  if (post.distillation_filter) lines.push(`Filter:      ${post.distillation_filter}`);
  if (post.content_channel) lines.push(`Channel:     ${post.content_channel}`);
  lines.push('');

  const caption = post.caption_text ?? '';
  const hashtags = post.hashtags ?? '';
  const hook = post.hook ?? '';

  for (const ch of post.channels) {
    const meta = CHANNEL_META[ch];
    if (!meta) continue;

    lines.push(sectionDiv);
    lines.push(`  ${meta.label.toUpperCase()}`);
    lines.push(sectionDiv);
    lines.push('');

    if (ch === 'twitter') {
      const tweetText = hook.length > 0 ? hook : caption.substring(0, 280);
      lines.push('Tweet text (≤280 chars):');
      lines.push('');
      lines.push(tweetText.substring(0, 280));
      lines.push('');
      lines.push(`Characters: ${Math.min(tweetText.length, 280)}/280`);
    } else if (ch === 'instagram') {
      lines.push('Caption:');
      lines.push('');
      lines.push(caption);
      if (hashtags) {
        lines.push('');
        lines.push(hashtags);
      }
      lines.push('');
      lines.push(`Characters: ${caption.length + (hashtags ? hashtags.length + 2 : 0)}/2200`);
    } else {
      lines.push('Post text:');
      lines.push('');
      lines.push(caption);
    }

    lines.push('');
    lines.push(`Image: ${ch}_*.png (${meta.dimensions})`);
    if (post.cta_link) {
      lines.push(`CTA:   ${post.cta_link}`);
    }
    lines.push('');
  }

  lines.push(sectionDiv);
  lines.push('  Generated by Bharatvarsh Content Pipeline');
  lines.push(`  ${new Date().toISOString()}`);
  lines.push(sectionDiv);

  return lines.join('\n');
}

/** GET /api/content-pipeline/[postId]/download-pack — Download ZIP with renders + post copy */
export async function GET(
  _req: Request,
  { params }: { params: Promise<{ postId: string }> },
) {
  try {
    const { postId } = await params;

    const post = await queryOne<ContentPost>(
      `SELECT * FROM content_posts WHERE post_id = $1`,
      [postId],
    );

    if (!post) {
      return NextResponse.json({ error: 'Post not found' }, { status: 404 });
    }

    const renderDir = path.join(
      getContentPipelineRoot(), 'rendered', postId,
    );

    let renderFiles: string[];
    try {
      renderFiles = (await readdir(renderDir)).filter(f => f.endsWith('.png'));
    } catch {
      return NextResponse.json({ error: 'No rendered files found. Render the post first.' }, { status: 404 });
    }

    if (renderFiles.length === 0) {
      return NextResponse.json({ error: 'No rendered PNG files found.' }, { status: 404 });
    }

    // Build ZIP in memory
    const passthrough = new PassThrough();
    const archive = archiver('zip', { zlib: { level: 5 } });
    archive.pipe(passthrough);

    // Add rendered images
    for (const file of renderFiles) {
      const filePath = path.join(renderDir, file);
      const buffer = await readFile(filePath);
      archive.append(buffer, { name: `images/${file}` });
    }

    // Add post copy text file
    const postCopyText = buildPostCopyText(post);
    archive.append(postCopyText, { name: 'post-copy.txt' });

    // Add render manifest if exists
    const manifestPath = path.join(renderDir, 'render-manifest.json');
    try {
      const manifestBuf = await readFile(manifestPath);
      archive.append(manifestBuf, { name: 'render-manifest.json' });
    } catch {
      // No manifest — skip
    }

    await archive.finalize();

    // Collect all chunks from the passthrough stream
    const chunks: Buffer[] = [];
    for await (const chunk of passthrough) {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    }
    const zipBuffer = Buffer.concat(chunks);

    const filename = `${postId}-post-pack.zip`;

    return new NextResponse(zipBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': String(zipBuffer.length),
        'Cache-Control': 'no-store',
      },
    });
  } catch (err) {
    console.error('[api/content-pipeline/[postId]/download-pack] Error:', err);
    return NextResponse.json({ error: 'Failed to generate post pack' }, { status: 500 });
  }
}
